# Generated by Django 5.0.4 on 2024-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivorcompass", "0004_asignatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="descripcion",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="asignatura",
            name="nombre",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
