# Generated by Django 5.0.4 on 2024-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivorcompass", "0005_asignatura_descripcion_alter_asignatura_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="foto",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
